### ISSUE TITLE
renaming sink

### ISSUE THREAD

**Issue by Shmerlard** [luisbocanegra/linux-guide-split-audio-ports#16]
hi, i followed the guide again after reinstalling arch and everything now works again, but i've noticed that the names of the sinks are different
![image](https://github.com/luisbocanegra/linux-guide-split-audio-ports/assets/5156442/8042b297-dfa4-4aba-8995-d6bc868be6f3)
how can one change it?
i want to set analog to speakers and 'alt analog' to headphones

**Comment by luisbocanegra** [comment]
Hi, this is a change coming from KDE Plasma, they changed the name source to make it easier to tell which device each port comes from.

You can rename the devices `nick` through pipewire

Create the file `~/.config/wireplumber/wireplumber.conf.d/custom-names.conf` with the following, replacing card name and node name with what you get running `pactl list sinks | grep -E "node.name|api.alsa.card.name"`:

```ini
monitor.alsa.rules = [
    {
        matches = [
            {
                api.alsa.card.name = "HDA Intel PCH",
                node.name = "~alsa_output.*stereo-headphones"
            }
        ]
        actions = {
            update-props = {
                node.nick              = "Headphones"
            }
        }
    }
    {
        matches = [
            {
                api.alsa.card.name = "HDA Intel PCH",
                node.name = "~alsa_output.*stereo-speaker"
            }
        ]
        actions = {
            update-props = {
                node.nick              = "Speakers"
            }
        }
    }
]
```

**Comment by Shmerlard** [comment]
Seriously man I cant thank you enough!
